# Copyright Waterford Institute of Technology 2017~2019
# Telecommunications Software and Systems Group (TSSG)
# Author Miguel Ponce de Leon <miguelpdl@tssg.org>
#
# Build a container via the example command
#      > make build
#
#
# Need to ensure the Docker daemon is running before the build will run

all:: build

build: 
	  docker build --rm -t tssg/libiec61850 .
